// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimerCache.proto

package com.game.framework.dbcache.model;

public final class TimerCache {
  private TimerCache() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoTimerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional int64 uid = 2;
    /**
     * <code>optional int64 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int64 uid = 2;</code>
     */
    long getUid();

    // optional int32 cmd = 3;
    /**
     * <code>optional int32 cmd = 3;</code>
     */
    boolean hasCmd();
    /**
     * <code>optional int32 cmd = 3;</code>
     */
    int getCmd();

    // optional string timerKey = 4;
    /**
     * <code>optional string timerKey = 4;</code>
     */
    boolean hasTimerKey();
    /**
     * <code>optional string timerKey = 4;</code>
     */
    java.lang.String getTimerKey();
    /**
     * <code>optional string timerKey = 4;</code>
     */
    com.google.protobuf.ByteString
        getTimerKeyBytes();

    // optional sint64 startTime = 5;
    /**
     * <code>optional sint64 startTime = 5;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional sint64 startTime = 5;</code>
     */
    long getStartTime();

    // optional int32 delay = 6;
    /**
     * <code>optional int32 delay = 6;</code>
     */
    boolean hasDelay();
    /**
     * <code>optional int32 delay = 6;</code>
     */
    int getDelay();

    // optional bytes timerData = 7;
    /**
     * <code>optional bytes timerData = 7;</code>
     */
    boolean hasTimerData();
    /**
     * <code>optional bytes timerData = 7;</code>
     */
    com.google.protobuf.ByteString getTimerData();
  }
  /**
   * Protobuf type {@code com.game.framework.dbcache.model.ProtoTimer}
   */
  public static final class ProtoTimer extends
      com.google.protobuf.GeneratedMessage
      implements ProtoTimerOrBuilder {
    // Use ProtoTimer.newBuilder() to construct.
    private ProtoTimer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoTimer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoTimer defaultInstance;
    public static ProtoTimer getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoTimer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoTimer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cmd_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              timerKey_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              startTime_ = input.readSInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              delay_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              timerData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.dbcache.model.TimerCache.internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.dbcache.model.TimerCache.internal_static_com_game_framework_dbcache_model_ProtoTimer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.dbcache.model.TimerCache.ProtoTimer.class, com.game.framework.dbcache.model.TimerCache.ProtoTimer.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoTimer> PARSER =
        new com.google.protobuf.AbstractParser<ProtoTimer>() {
      public ProtoTimer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoTimer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoTimer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional int64 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <code>optional int64 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 uid = 2;</code>
     */
    public long getUid() {
      return uid_;
    }

    // optional int32 cmd = 3;
    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 3;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 cmd = 3;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional string timerKey = 4;
    public static final int TIMERKEY_FIELD_NUMBER = 4;
    private java.lang.Object timerKey_;
    /**
     * <code>optional string timerKey = 4;</code>
     */
    public boolean hasTimerKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string timerKey = 4;</code>
     */
    public java.lang.String getTimerKey() {
      java.lang.Object ref = timerKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timerKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timerKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimerKeyBytes() {
      java.lang.Object ref = timerKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timerKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional sint64 startTime = 5;
    public static final int STARTTIME_FIELD_NUMBER = 5;
    private long startTime_;
    /**
     * <code>optional sint64 startTime = 5;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional sint64 startTime = 5;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    // optional int32 delay = 6;
    public static final int DELAY_FIELD_NUMBER = 6;
    private int delay_;
    /**
     * <code>optional int32 delay = 6;</code>
     */
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 delay = 6;</code>
     */
    public int getDelay() {
      return delay_;
    }

    // optional bytes timerData = 7;
    public static final int TIMERDATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString timerData_;
    /**
     * <code>optional bytes timerData = 7;</code>
     */
    public boolean hasTimerData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes timerData = 7;</code>
     */
    public com.google.protobuf.ByteString getTimerData() {
      return timerData_;
    }

    private void initFields() {
      id_ = 0L;
      uid_ = 0L;
      cmd_ = 0;
      timerKey_ = "";
      startTime_ = 0L;
      delay_ = 0;
      timerData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimerKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt64(5, startTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, delay_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, timerData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimerKeyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(5, startTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, delay_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, timerData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.dbcache.model.TimerCache.ProtoTimer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.dbcache.model.TimerCache.ProtoTimer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.dbcache.model.ProtoTimer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.dbcache.model.TimerCache.ProtoTimerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.dbcache.model.TimerCache.internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.dbcache.model.TimerCache.internal_static_com_game_framework_dbcache_model_ProtoTimer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.dbcache.model.TimerCache.ProtoTimer.class, com.game.framework.dbcache.model.TimerCache.ProtoTimer.Builder.class);
      }

      // Construct using com.game.framework.dbcache.model.TimerCache.ProtoTimer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        timerKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        timerData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.dbcache.model.TimerCache.internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor;
      }

      public com.game.framework.dbcache.model.TimerCache.ProtoTimer getDefaultInstanceForType() {
        return com.game.framework.dbcache.model.TimerCache.ProtoTimer.getDefaultInstance();
      }

      public com.game.framework.dbcache.model.TimerCache.ProtoTimer build() {
        com.game.framework.dbcache.model.TimerCache.ProtoTimer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.dbcache.model.TimerCache.ProtoTimer buildPartial() {
        com.game.framework.dbcache.model.TimerCache.ProtoTimer result = new com.game.framework.dbcache.model.TimerCache.ProtoTimer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timerKey_ = timerKey_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.delay_ = delay_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timerData_ = timerData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.dbcache.model.TimerCache.ProtoTimer) {
          return mergeFrom((com.game.framework.dbcache.model.TimerCache.ProtoTimer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.dbcache.model.TimerCache.ProtoTimer other) {
        if (other == com.game.framework.dbcache.model.TimerCache.ProtoTimer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasTimerKey()) {
          bitField0_ |= 0x00000008;
          timerKey_ = other.timerKey_;
          onChanged();
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        if (other.hasTimerData()) {
          setTimerData(other.getTimerData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.dbcache.model.TimerCache.ProtoTimer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.dbcache.model.TimerCache.ProtoTimer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 uid = 2;
      private long uid_ ;
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 cmd = 3;
      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 3;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 cmd = 3;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 3;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 3;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional string timerKey = 4;
      private java.lang.Object timerKey_ = "";
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public boolean hasTimerKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public java.lang.String getTimerKey() {
        java.lang.Object ref = timerKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timerKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTimerKeyBytes() {
        java.lang.Object ref = timerKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timerKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public Builder setTimerKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public Builder clearTimerKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timerKey_ = getDefaultInstance().getTimerKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timerKey = 4;</code>
       */
      public Builder setTimerKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timerKey_ = value;
        onChanged();
        return this;
      }

      // optional sint64 startTime = 5;
      private long startTime_ ;
      /**
       * <code>optional sint64 startTime = 5;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional sint64 startTime = 5;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional sint64 startTime = 5;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 startTime = 5;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 delay = 6;
      private int delay_ ;
      /**
       * <code>optional int32 delay = 6;</code>
       */
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 delay = 6;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>optional int32 delay = 6;</code>
       */
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000020;
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 delay = 6;</code>
       */
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000020);
        delay_ = 0;
        onChanged();
        return this;
      }

      // optional bytes timerData = 7;
      private com.google.protobuf.ByteString timerData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes timerData = 7;</code>
       */
      public boolean hasTimerData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes timerData = 7;</code>
       */
      public com.google.protobuf.ByteString getTimerData() {
        return timerData_;
      }
      /**
       * <code>optional bytes timerData = 7;</code>
       */
      public Builder setTimerData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        timerData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes timerData = 7;</code>
       */
      public Builder clearTimerData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timerData_ = getDefaultInstance().getTimerData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.dbcache.model.ProtoTimer)
    }

    static {
      defaultInstance = new ProtoTimer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.dbcache.model.ProtoTimer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_dbcache_model_ProtoTimer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TimerCache.proto\022 com.game.framework.d" +
      "bcache.model\"y\n\nProtoTimer\022\n\n\002id\030\001 \001(\003\022\013" +
      "\n\003uid\030\002 \001(\003\022\013\n\003cmd\030\003 \001(\005\022\020\n\010timerKey\030\004 \001" +
      "(\t\022\021\n\tstartTime\030\005 \001(\022\022\r\n\005delay\030\006 \001(\005\022\021\n\t" +
      "timerData\030\007 \001(\014B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_framework_dbcache_model_ProtoTimer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_dbcache_model_ProtoTimer_descriptor,
              new java.lang.String[] { "Id", "Uid", "Cmd", "TimerKey", "StartTime", "Delay", "TimerData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
