// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserCache.proto

package com.game.framework.dbcache.model;

public final class UserCache {
  private UserCache() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoUserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional string account = 2;
    /**
     * <code>optional string account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>optional string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // optional string password = 3;
    /**
     * <code>optional string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional int64 groupId = 4;
    /**
     * <code>optional int64 groupId = 4;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional int64 groupId = 4;</code>
     */
    long getGroupId();

    // optional int32 contribution = 5;
    /**
     * <code>optional int32 contribution = 5;</code>
     */
    boolean hasContribution();
    /**
     * <code>optional int32 contribution = 5;</code>
     */
    int getContribution();

    // optional double gold = 6;
    /**
     * <code>optional double gold = 6;</code>
     */
    boolean hasGold();
    /**
     * <code>optional double gold = 6;</code>
     */
    double getGold();

    // optional int32 blood = 7;
    /**
     * <code>optional int32 blood = 7;</code>
     */
    boolean hasBlood();
    /**
     * <code>optional int32 blood = 7;</code>
     */
    int getBlood();

    // optional int32 food = 8;
    /**
     * <code>optional int32 food = 8;</code>
     */
    boolean hasFood();
    /**
     * <code>optional int32 food = 8;</code>
     */
    int getFood();

    // optional int32 water = 9;
    /**
     * <code>optional int32 water = 9;</code>
     */
    boolean hasWater();
    /**
     * <code>optional int32 water = 9;</code>
     */
    int getWater();

    // optional int32 health = 10;
    /**
     * <code>optional int32 health = 10;</code>
     */
    boolean hasHealth();
    /**
     * <code>optional int32 health = 10;</code>
     */
    int getHealth();

    // optional int32 mood = 11;
    /**
     * <code>optional int32 mood = 11;</code>
     */
    boolean hasMood();
    /**
     * <code>optional int32 mood = 11;</code>
     */
    int getMood();

    // optional int32 attack = 12;
    /**
     * <code>optional int32 attack = 12;</code>
     */
    boolean hasAttack();
    /**
     * <code>optional int32 attack = 12;</code>
     */
    int getAttack();

    // optional int32 defense = 13;
    /**
     * <code>optional int32 defense = 13;</code>
     */
    boolean hasDefense();
    /**
     * <code>optional int32 defense = 13;</code>
     */
    int getDefense();

    // optional int32 agile = 14;
    /**
     * <code>optional int32 agile = 14;</code>
     */
    boolean hasAgile();
    /**
     * <code>optional int32 agile = 14;</code>
     */
    int getAgile();

    // optional int32 speed = 15;
    /**
     * <code>optional int32 speed = 15;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional int32 speed = 15;</code>
     */
    int getSpeed();

    // optional int32 intellect = 16;
    /**
     * <code>optional int32 intellect = 16;</code>
     */
    boolean hasIntellect();
    /**
     * <code>optional int32 intellect = 16;</code>
     */
    int getIntellect();

    // optional int32 electricity = 17;
    /**
     * <code>optional int32 electricity = 17;</code>
     */
    boolean hasElectricity();
    /**
     * <code>optional int32 electricity = 17;</code>
     */
    int getElectricity();

    // optional int32 production = 18;
    /**
     * <code>optional int32 production = 18;</code>
     */
    boolean hasProduction();
    /**
     * <code>optional int32 production = 18;</code>
     */
    int getProduction();

    // optional sint64 createTime = 19;
    /**
     * <code>optional sint64 createTime = 19;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>optional sint64 createTime = 19;</code>
     */
    long getCreateTime();

    // optional sint64 logoutTime = 20;
    /**
     * <code>optional sint64 logoutTime = 20;</code>
     */
    boolean hasLogoutTime();
    /**
     * <code>optional sint64 logoutTime = 20;</code>
     */
    long getLogoutTime();

    // optional bytes resource = 21;
    /**
     * <code>optional bytes resource = 21;</code>
     */
    boolean hasResource();
    /**
     * <code>optional bytes resource = 21;</code>
     */
    com.google.protobuf.ByteString getResource();
  }
  /**
   * Protobuf type {@code com.game.framework.dbcache.model.ProtoUser}
   */
  public static final class ProtoUser extends
      com.google.protobuf.GeneratedMessage
      implements ProtoUserOrBuilder {
    // Use ProtoUser.newBuilder() to construct.
    private ProtoUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoUser defaultInstance;
    public static ProtoUser getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              groupId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              contribution_ = input.readInt32();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              gold_ = input.readDouble();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              blood_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              food_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              water_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              health_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              mood_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              attack_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              defense_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              agile_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              speed_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              intellect_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              electricity_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              production_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              createTime_ = input.readSInt64();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              logoutTime_ = input.readSInt64();
              break;
            }
            case 170: {
              bitField0_ |= 0x00100000;
              resource_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.dbcache.model.UserCache.internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.dbcache.model.UserCache.internal_static_com_game_framework_dbcache_model_ProtoUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.dbcache.model.UserCache.ProtoUser.class, com.game.framework.dbcache.model.UserCache.ProtoUser.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoUser> PARSER =
        new com.google.protobuf.AbstractParser<ProtoUser>() {
      public ProtoUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoUser(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    /**
     * <code>optional string account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 groupId = 4;
    public static final int GROUPID_FIELD_NUMBER = 4;
    private long groupId_;
    /**
     * <code>optional int64 groupId = 4;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 groupId = 4;</code>
     */
    public long getGroupId() {
      return groupId_;
    }

    // optional int32 contribution = 5;
    public static final int CONTRIBUTION_FIELD_NUMBER = 5;
    private int contribution_;
    /**
     * <code>optional int32 contribution = 5;</code>
     */
    public boolean hasContribution() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 contribution = 5;</code>
     */
    public int getContribution() {
      return contribution_;
    }

    // optional double gold = 6;
    public static final int GOLD_FIELD_NUMBER = 6;
    private double gold_;
    /**
     * <code>optional double gold = 6;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double gold = 6;</code>
     */
    public double getGold() {
      return gold_;
    }

    // optional int32 blood = 7;
    public static final int BLOOD_FIELD_NUMBER = 7;
    private int blood_;
    /**
     * <code>optional int32 blood = 7;</code>
     */
    public boolean hasBlood() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 blood = 7;</code>
     */
    public int getBlood() {
      return blood_;
    }

    // optional int32 food = 8;
    public static final int FOOD_FIELD_NUMBER = 8;
    private int food_;
    /**
     * <code>optional int32 food = 8;</code>
     */
    public boolean hasFood() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 food = 8;</code>
     */
    public int getFood() {
      return food_;
    }

    // optional int32 water = 9;
    public static final int WATER_FIELD_NUMBER = 9;
    private int water_;
    /**
     * <code>optional int32 water = 9;</code>
     */
    public boolean hasWater() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 water = 9;</code>
     */
    public int getWater() {
      return water_;
    }

    // optional int32 health = 10;
    public static final int HEALTH_FIELD_NUMBER = 10;
    private int health_;
    /**
     * <code>optional int32 health = 10;</code>
     */
    public boolean hasHealth() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 health = 10;</code>
     */
    public int getHealth() {
      return health_;
    }

    // optional int32 mood = 11;
    public static final int MOOD_FIELD_NUMBER = 11;
    private int mood_;
    /**
     * <code>optional int32 mood = 11;</code>
     */
    public boolean hasMood() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 mood = 11;</code>
     */
    public int getMood() {
      return mood_;
    }

    // optional int32 attack = 12;
    public static final int ATTACK_FIELD_NUMBER = 12;
    private int attack_;
    /**
     * <code>optional int32 attack = 12;</code>
     */
    public boolean hasAttack() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 attack = 12;</code>
     */
    public int getAttack() {
      return attack_;
    }

    // optional int32 defense = 13;
    public static final int DEFENSE_FIELD_NUMBER = 13;
    private int defense_;
    /**
     * <code>optional int32 defense = 13;</code>
     */
    public boolean hasDefense() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 defense = 13;</code>
     */
    public int getDefense() {
      return defense_;
    }

    // optional int32 agile = 14;
    public static final int AGILE_FIELD_NUMBER = 14;
    private int agile_;
    /**
     * <code>optional int32 agile = 14;</code>
     */
    public boolean hasAgile() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 agile = 14;</code>
     */
    public int getAgile() {
      return agile_;
    }

    // optional int32 speed = 15;
    public static final int SPEED_FIELD_NUMBER = 15;
    private int speed_;
    /**
     * <code>optional int32 speed = 15;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 speed = 15;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    // optional int32 intellect = 16;
    public static final int INTELLECT_FIELD_NUMBER = 16;
    private int intellect_;
    /**
     * <code>optional int32 intellect = 16;</code>
     */
    public boolean hasIntellect() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 intellect = 16;</code>
     */
    public int getIntellect() {
      return intellect_;
    }

    // optional int32 electricity = 17;
    public static final int ELECTRICITY_FIELD_NUMBER = 17;
    private int electricity_;
    /**
     * <code>optional int32 electricity = 17;</code>
     */
    public boolean hasElectricity() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int32 electricity = 17;</code>
     */
    public int getElectricity() {
      return electricity_;
    }

    // optional int32 production = 18;
    public static final int PRODUCTION_FIELD_NUMBER = 18;
    private int production_;
    /**
     * <code>optional int32 production = 18;</code>
     */
    public boolean hasProduction() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional int32 production = 18;</code>
     */
    public int getProduction() {
      return production_;
    }

    // optional sint64 createTime = 19;
    public static final int CREATETIME_FIELD_NUMBER = 19;
    private long createTime_;
    /**
     * <code>optional sint64 createTime = 19;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional sint64 createTime = 19;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    // optional sint64 logoutTime = 20;
    public static final int LOGOUTTIME_FIELD_NUMBER = 20;
    private long logoutTime_;
    /**
     * <code>optional sint64 logoutTime = 20;</code>
     */
    public boolean hasLogoutTime() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional sint64 logoutTime = 20;</code>
     */
    public long getLogoutTime() {
      return logoutTime_;
    }

    // optional bytes resource = 21;
    public static final int RESOURCE_FIELD_NUMBER = 21;
    private com.google.protobuf.ByteString resource_;
    /**
     * <code>optional bytes resource = 21;</code>
     */
    public boolean hasResource() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional bytes resource = 21;</code>
     */
    public com.google.protobuf.ByteString getResource() {
      return resource_;
    }

    private void initFields() {
      id_ = 0L;
      account_ = "";
      password_ = "";
      groupId_ = 0L;
      contribution_ = 0;
      gold_ = 0D;
      blood_ = 0;
      food_ = 0;
      water_ = 0;
      health_ = 0;
      mood_ = 0;
      attack_ = 0;
      defense_ = 0;
      agile_ = 0;
      speed_ = 0;
      intellect_ = 0;
      electricity_ = 0;
      production_ = 0;
      createTime_ = 0L;
      logoutTime_ = 0L;
      resource_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, contribution_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, gold_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, blood_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, food_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, water_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, health_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, mood_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, attack_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, defense_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, agile_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, speed_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, intellect_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, electricity_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(18, production_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeSInt64(19, createTime_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeSInt64(20, logoutTime_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, resource_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, contribution_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, gold_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, blood_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, food_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, water_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, health_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, mood_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, attack_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, defense_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, agile_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, speed_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, intellect_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, electricity_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, production_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(19, createTime_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(20, logoutTime_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, resource_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.dbcache.model.UserCache.ProtoUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.dbcache.model.UserCache.ProtoUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.dbcache.model.ProtoUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.dbcache.model.UserCache.ProtoUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.dbcache.model.UserCache.internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.dbcache.model.UserCache.internal_static_com_game_framework_dbcache_model_ProtoUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.dbcache.model.UserCache.ProtoUser.class, com.game.framework.dbcache.model.UserCache.ProtoUser.Builder.class);
      }

      // Construct using com.game.framework.dbcache.model.UserCache.ProtoUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        groupId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        contribution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        gold_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        blood_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        food_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        water_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        health_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        mood_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        attack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        defense_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        agile_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        intellect_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        electricity_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        production_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00040000);
        logoutTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00080000);
        resource_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00100000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.dbcache.model.UserCache.internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor;
      }

      public com.game.framework.dbcache.model.UserCache.ProtoUser getDefaultInstanceForType() {
        return com.game.framework.dbcache.model.UserCache.ProtoUser.getDefaultInstance();
      }

      public com.game.framework.dbcache.model.UserCache.ProtoUser build() {
        com.game.framework.dbcache.model.UserCache.ProtoUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.dbcache.model.UserCache.ProtoUser buildPartial() {
        com.game.framework.dbcache.model.UserCache.ProtoUser result = new com.game.framework.dbcache.model.UserCache.ProtoUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.contribution_ = contribution_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.blood_ = blood_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.food_ = food_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.water_ = water_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.health_ = health_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.mood_ = mood_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.attack_ = attack_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.defense_ = defense_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.agile_ = agile_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.intellect_ = intellect_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.electricity_ = electricity_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.production_ = production_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.logoutTime_ = logoutTime_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.resource_ = resource_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.dbcache.model.UserCache.ProtoUser) {
          return mergeFrom((com.game.framework.dbcache.model.UserCache.ProtoUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.dbcache.model.UserCache.ProtoUser other) {
        if (other == com.game.framework.dbcache.model.UserCache.ProtoUser.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        if (other.hasContribution()) {
          setContribution(other.getContribution());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasBlood()) {
          setBlood(other.getBlood());
        }
        if (other.hasFood()) {
          setFood(other.getFood());
        }
        if (other.hasWater()) {
          setWater(other.getWater());
        }
        if (other.hasHealth()) {
          setHealth(other.getHealth());
        }
        if (other.hasMood()) {
          setMood(other.getMood());
        }
        if (other.hasAttack()) {
          setAttack(other.getAttack());
        }
        if (other.hasDefense()) {
          setDefense(other.getDefense());
        }
        if (other.hasAgile()) {
          setAgile(other.getAgile());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasIntellect()) {
          setIntellect(other.getIntellect());
        }
        if (other.hasElectricity()) {
          setElectricity(other.getElectricity());
        }
        if (other.hasProduction()) {
          setProduction(other.getProduction());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasLogoutTime()) {
          setLogoutTime(other.getLogoutTime());
        }
        if (other.hasResource()) {
          setResource(other.getResource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.dbcache.model.UserCache.ProtoUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.dbcache.model.UserCache.ProtoUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional string account = 2;
      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      // optional string password = 3;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      // optional int64 groupId = 4;
      private long groupId_ ;
      /**
       * <code>optional int64 groupId = 4;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 groupId = 4;</code>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int64 groupId = 4;</code>
       */
      public Builder setGroupId(long value) {
        bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 groupId = 4;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 contribution = 5;
      private int contribution_ ;
      /**
       * <code>optional int32 contribution = 5;</code>
       */
      public boolean hasContribution() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 contribution = 5;</code>
       */
      public int getContribution() {
        return contribution_;
      }
      /**
       * <code>optional int32 contribution = 5;</code>
       */
      public Builder setContribution(int value) {
        bitField0_ |= 0x00000010;
        contribution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contribution = 5;</code>
       */
      public Builder clearContribution() {
        bitField0_ = (bitField0_ & ~0x00000010);
        contribution_ = 0;
        onChanged();
        return this;
      }

      // optional double gold = 6;
      private double gold_ ;
      /**
       * <code>optional double gold = 6;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double gold = 6;</code>
       */
      public double getGold() {
        return gold_;
      }
      /**
       * <code>optional double gold = 6;</code>
       */
      public Builder setGold(double value) {
        bitField0_ |= 0x00000020;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double gold = 6;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gold_ = 0D;
        onChanged();
        return this;
      }

      // optional int32 blood = 7;
      private int blood_ ;
      /**
       * <code>optional int32 blood = 7;</code>
       */
      public boolean hasBlood() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 blood = 7;</code>
       */
      public int getBlood() {
        return blood_;
      }
      /**
       * <code>optional int32 blood = 7;</code>
       */
      public Builder setBlood(int value) {
        bitField0_ |= 0x00000040;
        blood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 blood = 7;</code>
       */
      public Builder clearBlood() {
        bitField0_ = (bitField0_ & ~0x00000040);
        blood_ = 0;
        onChanged();
        return this;
      }

      // optional int32 food = 8;
      private int food_ ;
      /**
       * <code>optional int32 food = 8;</code>
       */
      public boolean hasFood() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 food = 8;</code>
       */
      public int getFood() {
        return food_;
      }
      /**
       * <code>optional int32 food = 8;</code>
       */
      public Builder setFood(int value) {
        bitField0_ |= 0x00000080;
        food_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 food = 8;</code>
       */
      public Builder clearFood() {
        bitField0_ = (bitField0_ & ~0x00000080);
        food_ = 0;
        onChanged();
        return this;
      }

      // optional int32 water = 9;
      private int water_ ;
      /**
       * <code>optional int32 water = 9;</code>
       */
      public boolean hasWater() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 water = 9;</code>
       */
      public int getWater() {
        return water_;
      }
      /**
       * <code>optional int32 water = 9;</code>
       */
      public Builder setWater(int value) {
        bitField0_ |= 0x00000100;
        water_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 water = 9;</code>
       */
      public Builder clearWater() {
        bitField0_ = (bitField0_ & ~0x00000100);
        water_ = 0;
        onChanged();
        return this;
      }

      // optional int32 health = 10;
      private int health_ ;
      /**
       * <code>optional int32 health = 10;</code>
       */
      public boolean hasHealth() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 health = 10;</code>
       */
      public int getHealth() {
        return health_;
      }
      /**
       * <code>optional int32 health = 10;</code>
       */
      public Builder setHealth(int value) {
        bitField0_ |= 0x00000200;
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 health = 10;</code>
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00000200);
        health_ = 0;
        onChanged();
        return this;
      }

      // optional int32 mood = 11;
      private int mood_ ;
      /**
       * <code>optional int32 mood = 11;</code>
       */
      public boolean hasMood() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 mood = 11;</code>
       */
      public int getMood() {
        return mood_;
      }
      /**
       * <code>optional int32 mood = 11;</code>
       */
      public Builder setMood(int value) {
        bitField0_ |= 0x00000400;
        mood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mood = 11;</code>
       */
      public Builder clearMood() {
        bitField0_ = (bitField0_ & ~0x00000400);
        mood_ = 0;
        onChanged();
        return this;
      }

      // optional int32 attack = 12;
      private int attack_ ;
      /**
       * <code>optional int32 attack = 12;</code>
       */
      public boolean hasAttack() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 attack = 12;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>optional int32 attack = 12;</code>
       */
      public Builder setAttack(int value) {
        bitField0_ |= 0x00000800;
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 attack = 12;</code>
       */
      public Builder clearAttack() {
        bitField0_ = (bitField0_ & ~0x00000800);
        attack_ = 0;
        onChanged();
        return this;
      }

      // optional int32 defense = 13;
      private int defense_ ;
      /**
       * <code>optional int32 defense = 13;</code>
       */
      public boolean hasDefense() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 defense = 13;</code>
       */
      public int getDefense() {
        return defense_;
      }
      /**
       * <code>optional int32 defense = 13;</code>
       */
      public Builder setDefense(int value) {
        bitField0_ |= 0x00001000;
        defense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 defense = 13;</code>
       */
      public Builder clearDefense() {
        bitField0_ = (bitField0_ & ~0x00001000);
        defense_ = 0;
        onChanged();
        return this;
      }

      // optional int32 agile = 14;
      private int agile_ ;
      /**
       * <code>optional int32 agile = 14;</code>
       */
      public boolean hasAgile() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 agile = 14;</code>
       */
      public int getAgile() {
        return agile_;
      }
      /**
       * <code>optional int32 agile = 14;</code>
       */
      public Builder setAgile(int value) {
        bitField0_ |= 0x00002000;
        agile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 agile = 14;</code>
       */
      public Builder clearAgile() {
        bitField0_ = (bitField0_ & ~0x00002000);
        agile_ = 0;
        onChanged();
        return this;
      }

      // optional int32 speed = 15;
      private int speed_ ;
      /**
       * <code>optional int32 speed = 15;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 speed = 15;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>optional int32 speed = 15;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00004000;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 speed = 15;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00004000);
        speed_ = 0;
        onChanged();
        return this;
      }

      // optional int32 intellect = 16;
      private int intellect_ ;
      /**
       * <code>optional int32 intellect = 16;</code>
       */
      public boolean hasIntellect() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 intellect = 16;</code>
       */
      public int getIntellect() {
        return intellect_;
      }
      /**
       * <code>optional int32 intellect = 16;</code>
       */
      public Builder setIntellect(int value) {
        bitField0_ |= 0x00008000;
        intellect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intellect = 16;</code>
       */
      public Builder clearIntellect() {
        bitField0_ = (bitField0_ & ~0x00008000);
        intellect_ = 0;
        onChanged();
        return this;
      }

      // optional int32 electricity = 17;
      private int electricity_ ;
      /**
       * <code>optional int32 electricity = 17;</code>
       */
      public boolean hasElectricity() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int32 electricity = 17;</code>
       */
      public int getElectricity() {
        return electricity_;
      }
      /**
       * <code>optional int32 electricity = 17;</code>
       */
      public Builder setElectricity(int value) {
        bitField0_ |= 0x00010000;
        electricity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 electricity = 17;</code>
       */
      public Builder clearElectricity() {
        bitField0_ = (bitField0_ & ~0x00010000);
        electricity_ = 0;
        onChanged();
        return this;
      }

      // optional int32 production = 18;
      private int production_ ;
      /**
       * <code>optional int32 production = 18;</code>
       */
      public boolean hasProduction() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional int32 production = 18;</code>
       */
      public int getProduction() {
        return production_;
      }
      /**
       * <code>optional int32 production = 18;</code>
       */
      public Builder setProduction(int value) {
        bitField0_ |= 0x00020000;
        production_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 production = 18;</code>
       */
      public Builder clearProduction() {
        bitField0_ = (bitField0_ & ~0x00020000);
        production_ = 0;
        onChanged();
        return this;
      }

      // optional sint64 createTime = 19;
      private long createTime_ ;
      /**
       * <code>optional sint64 createTime = 19;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional sint64 createTime = 19;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional sint64 createTime = 19;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00040000;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 createTime = 19;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00040000);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // optional sint64 logoutTime = 20;
      private long logoutTime_ ;
      /**
       * <code>optional sint64 logoutTime = 20;</code>
       */
      public boolean hasLogoutTime() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional sint64 logoutTime = 20;</code>
       */
      public long getLogoutTime() {
        return logoutTime_;
      }
      /**
       * <code>optional sint64 logoutTime = 20;</code>
       */
      public Builder setLogoutTime(long value) {
        bitField0_ |= 0x00080000;
        logoutTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 logoutTime = 20;</code>
       */
      public Builder clearLogoutTime() {
        bitField0_ = (bitField0_ & ~0x00080000);
        logoutTime_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes resource = 21;
      private com.google.protobuf.ByteString resource_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes resource = 21;</code>
       */
      public boolean hasResource() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional bytes resource = 21;</code>
       */
      public com.google.protobuf.ByteString getResource() {
        return resource_;
      }
      /**
       * <code>optional bytes resource = 21;</code>
       */
      public Builder setResource(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        resource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes resource = 21;</code>
       */
      public Builder clearResource() {
        bitField0_ = (bitField0_ & ~0x00100000);
        resource_ = getDefaultInstance().getResource();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.dbcache.model.ProtoUser)
    }

    static {
      defaultInstance = new ProtoUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.dbcache.model.ProtoUser)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_dbcache_model_ProtoUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserCache.proto\022 com.game.framework.db" +
      "cache.model\"\356\002\n\tProtoUser\022\n\n\002id\030\001 \001(\003\022\017\n" +
      "\007account\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\017\n\007grou" +
      "pId\030\004 \001(\003\022\024\n\014contribution\030\005 \001(\005\022\014\n\004gold\030" +
      "\006 \001(\001\022\r\n\005blood\030\007 \001(\005\022\014\n\004food\030\010 \001(\005\022\r\n\005wa" +
      "ter\030\t \001(\005\022\016\n\006health\030\n \001(\005\022\014\n\004mood\030\013 \001(\005\022" +
      "\016\n\006attack\030\014 \001(\005\022\017\n\007defense\030\r \001(\005\022\r\n\005agil" +
      "e\030\016 \001(\005\022\r\n\005speed\030\017 \001(\005\022\021\n\tintellect\030\020 \001(" +
      "\005\022\023\n\013electricity\030\021 \001(\005\022\022\n\nproduction\030\022 \001" +
      "(\005\022\022\n\ncreateTime\030\023 \001(\022\022\022\n\nlogoutTime\030\024 \001",
      "(\022\022\020\n\010resource\030\025 \001(\014B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_framework_dbcache_model_ProtoUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_dbcache_model_ProtoUser_descriptor,
              new java.lang.String[] { "Id", "Account", "Password", "GroupId", "Contribution", "Gold", "Blood", "Food", "Water", "Health", "Mood", "Attack", "Defense", "Agile", "Speed", "Intellect", "Electricity", "Production", "CreateTime", "LogoutTime", "Resource", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
