// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/attrname_bytes.proto

package com.nkm.framework.resource.data;

public final class AttrnameBytes {
  private AttrnameBytes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ATTRNAMEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nkm.framework.resource.data.ATTRNAME)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    boolean hasAttrName();
    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    java.lang.String getAttrName();
    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    com.google.protobuf.ByteString
        getAttrNameBytes();

    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    boolean hasAttrUnits();
    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    java.lang.String getAttrUnits();
    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    com.google.protobuf.ByteString
        getAttrUnitsBytes();
  }
  /**
   * Protobuf type {@code com.nkm.framework.resource.data.ATTRNAME}
   */
  public static final class ATTRNAME extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.nkm.framework.resource.data.ATTRNAME)
      ATTRNAMEOrBuilder {
    // Use ATTRNAME.newBuilder() to construct.
    private ATTRNAME(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ATTRNAME(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ATTRNAME defaultInstance;
    public static ATTRNAME getDefaultInstance() {
      return defaultInstance;
    }

    public ATTRNAME getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ATTRNAME(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              attrName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              attrUnits_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.class, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder.class);
    }

    public static com.google.protobuf.Parser<ATTRNAME> PARSER =
        new com.google.protobuf.AbstractParser<ATTRNAME>() {
      public ATTRNAME parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ATTRNAME(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ATTRNAME> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1 [default = ""];</code>
     *
     * <pre>
     ** key 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTR_NAME_FIELD_NUMBER = 2;
    private java.lang.Object attrName_;
    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    public boolean hasAttrName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    public java.lang.String getAttrName() {
      java.lang.Object ref = attrName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attrName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string attr_name = 2 [default = ""];</code>
     *
     * <pre>
     ** 属性名称 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAttrNameBytes() {
      java.lang.Object ref = attrName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attrName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTR_UNITS_FIELD_NUMBER = 3;
    private java.lang.Object attrUnits_;
    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    public boolean hasAttrUnits() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    public java.lang.String getAttrUnits() {
      java.lang.Object ref = attrUnits_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attrUnits_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string attr_units = 3 [default = ""];</code>
     *
     * <pre>
     ** 属性单位 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAttrUnitsBytes() {
      java.lang.Object ref = attrUnits_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attrUnits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      attrName_ = "";
      attrUnits_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAttrNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAttrUnitsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAttrNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAttrUnitsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nkm.framework.resource.data.ATTRNAME}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nkm.framework.resource.data.ATTRNAME)
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.class, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder.class);
      }

      // Construct using com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        attrName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        attrUnits_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor;
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME getDefaultInstanceForType() {
        return com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.getDefaultInstance();
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME build() {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME buildPartial() {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME result = new com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attrName_ = attrName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attrUnits_ = attrUnits_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME) {
          return mergeFrom((com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME other) {
        if (other == com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasAttrName()) {
          bitField0_ |= 0x00000002;
          attrName_ = other.attrName_;
          onChanged();
        }
        if (other.hasAttrUnits()) {
          bitField0_ |= 0x00000004;
          attrUnits_ = other.attrUnits_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1 [default = ""];</code>
       *
       * <pre>
       ** key 
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object attrName_ = "";
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public boolean hasAttrName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public java.lang.String getAttrName() {
        java.lang.Object ref = attrName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attrName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAttrNameBytes() {
        java.lang.Object ref = attrName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attrName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public Builder setAttrName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attrName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public Builder clearAttrName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attrName_ = getDefaultInstance().getAttrName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string attr_name = 2 [default = ""];</code>
       *
       * <pre>
       ** 属性名称 
       * </pre>
       */
      public Builder setAttrNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attrName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object attrUnits_ = "";
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public boolean hasAttrUnits() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public java.lang.String getAttrUnits() {
        java.lang.Object ref = attrUnits_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attrUnits_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAttrUnitsBytes() {
        java.lang.Object ref = attrUnits_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attrUnits_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public Builder setAttrUnits(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        attrUnits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public Builder clearAttrUnits() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attrUnits_ = getDefaultInstance().getAttrUnits();
        onChanged();
        return this;
      }
      /**
       * <code>optional string attr_units = 3 [default = ""];</code>
       *
       * <pre>
       ** 属性单位 
       * </pre>
       */
      public Builder setAttrUnitsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        attrUnits_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nkm.framework.resource.data.ATTRNAME)
    }

    static {
      defaultInstance = new ATTRNAME(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nkm.framework.resource.data.ATTRNAME)
  }

  public interface ATTRNAME_ARRAYOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nkm.framework.resource.data.ATTRNAME_ARRAY)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> 
        getItemsList();
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME getItems(int index);
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    java.util.List<? extends com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.nkm.framework.resource.data.ATTRNAME_ARRAY}
   */
  public static final class ATTRNAME_ARRAY extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.nkm.framework.resource.data.ATTRNAME_ARRAY)
      ATTRNAME_ARRAYOrBuilder {
    // Use ATTRNAME_ARRAY.newBuilder() to construct.
    private ATTRNAME_ARRAY(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ATTRNAME_ARRAY(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ATTRNAME_ARRAY defaultInstance;
    public static ATTRNAME_ARRAY getDefaultInstance() {
      return defaultInstance;
    }

    public ATTRNAME_ARRAY getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ATTRNAME_ARRAY(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.class, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.Builder.class);
    }

    public static com.google.protobuf.Parser<ATTRNAME_ARRAY> PARSER =
        new com.google.protobuf.AbstractParser<ATTRNAME_ARRAY>() {
      public ATTRNAME_ARRAY parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ATTRNAME_ARRAY(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ATTRNAME_ARRAY> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> items_;
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    public java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    public java.util.List<? extends com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
     */
    public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nkm.framework.resource.data.ATTRNAME_ARRAY}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nkm.framework.resource.data.ATTRNAME_ARRAY)
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAYOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.class, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.Builder.class);
      }

      // Construct using com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nkm.framework.resource.data.AttrnameBytes.internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor;
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY getDefaultInstanceForType() {
        return com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.getDefaultInstance();
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY build() {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY buildPartial() {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY result = new com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY) {
          return mergeFrom((com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY other) {
        if (other == com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME_ARRAY) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder setItems(
          int index, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder setItems(
          int index, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder addItems(com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder addItems(
          int index, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder addItems(
          com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder addItems(
          int index, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public java.util.List<? extends com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.getDefaultInstance());
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.getDefaultInstance());
      }
      /**
       * <code>repeated .com.nkm.framework.resource.data.ATTRNAME items = 1;</code>
       */
      public java.util.List<com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAME.Builder, com.nkm.framework.resource.data.AttrnameBytes.ATTRNAMEOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.nkm.framework.resource.data.ATTRNAME_ARRAY)
    }

    static {
      defaultInstance = new ATTRNAME_ARRAY(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nkm.framework.resource.data.ATTRNAME_ARRAY)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nkm_framework_resource_data_ATTRNAME_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/attrname_bytes.proto\022\037com.nkm.fr" +
      "amework.resource.data\"C\n\010ATTRNAME\022\014\n\002id\030" +
      "\001 \002(\t:\000\022\023\n\tattr_name\030\002 \001(\t:\000\022\024\n\nattr_uni" +
      "ts\030\003 \001(\t:\000\"J\n\016ATTRNAME_ARRAY\0228\n\005items\030\001 " +
      "\003(\0132).com.nkm.framework.resource.data.AT" +
      "TRNAME"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nkm_framework_resource_data_ATTRNAME_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_nkm_framework_resource_data_ATTRNAME_descriptor,
        new java.lang.String[] { "Id", "AttrName", "AttrUnits", });
    internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_nkm_framework_resource_data_ATTRNAME_ARRAY_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
