# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mineral_fin_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/mineral_fin_data.proto',
  package='com.game.server.data',
  serialized_pb=_b('\n\x1cproto/mineral_fin_data.proto\x12\x14\x63om.game.server.data\"5\n\x0bMINERAL_FIN\x12\r\n\x02id\x18\x01 \x02(\x05:\x01\x30\x12\x17\n\x0cproduce_rate\x18\x02 \x01(\x05:\x01\x30\"E\n\x11MINERAL_FIN_ARRAY\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.com.game.server.data.MINERAL_FIN')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MINERAL_FIN = _descriptor.Descriptor(
  name='MINERAL_FIN',
  full_name='com.game.server.data.MINERAL_FIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.game.server.data.MINERAL_FIN.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='produce_rate', full_name='com.game.server.data.MINERAL_FIN.produce_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=107,
)


_MINERAL_FIN_ARRAY = _descriptor.Descriptor(
  name='MINERAL_FIN_ARRAY',
  full_name='com.game.server.data.MINERAL_FIN_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.game.server.data.MINERAL_FIN_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=178,
)

_MINERAL_FIN_ARRAY.fields_by_name['items'].message_type = _MINERAL_FIN
DESCRIPTOR.message_types_by_name['MINERAL_FIN'] = _MINERAL_FIN
DESCRIPTOR.message_types_by_name['MINERAL_FIN_ARRAY'] = _MINERAL_FIN_ARRAY

MINERAL_FIN = _reflection.GeneratedProtocolMessageType('MINERAL_FIN', (_message.Message,), dict(
  DESCRIPTOR = _MINERAL_FIN,
  __module__ = 'proto.mineral_fin_data_pb2'
  # @@protoc_insertion_point(class_scope:com.game.server.data.MINERAL_FIN)
  ))
_sym_db.RegisterMessage(MINERAL_FIN)

MINERAL_FIN_ARRAY = _reflection.GeneratedProtocolMessageType('MINERAL_FIN_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _MINERAL_FIN_ARRAY,
  __module__ = 'proto.mineral_fin_data_pb2'
  # @@protoc_insertion_point(class_scope:com.game.server.data.MINERAL_FIN_ARRAY)
  ))
_sym_db.RegisterMessage(MINERAL_FIN_ARRAY)


# @@protoc_insertion_point(module_scope)
