# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/siliao_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/siliao_data.proto',
  package='com.game.framework.resource.data',
  serialized_pb=_b('\n\x17proto/siliao_data.proto\x12 com.game.framework.resource.data\"K\n\x06SILIAO\x12\r\n\x02id\x18\x01 \x02(\x05:\x01\x30\x12\x1b\n\x10siliao_spd_coeff\x18\x02 \x01(\x05:\x01\x30\x12\x15\n\nsiliao_cap\x18\x03 \x01(\x05:\x01\x30\"G\n\x0cSILIAO_ARRAY\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.com.game.framework.resource.data.SILIAO')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SILIAO = _descriptor.Descriptor(
  name='SILIAO',
  full_name='com.game.framework.resource.data.SILIAO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.game.framework.resource.data.SILIAO.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siliao_spd_coeff', full_name='com.game.framework.resource.data.SILIAO.siliao_spd_coeff', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='siliao_cap', full_name='com.game.framework.resource.data.SILIAO.siliao_cap', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=136,
)


_SILIAO_ARRAY = _descriptor.Descriptor(
  name='SILIAO_ARRAY',
  full_name='com.game.framework.resource.data.SILIAO_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.game.framework.resource.data.SILIAO_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=209,
)

_SILIAO_ARRAY.fields_by_name['items'].message_type = _SILIAO
DESCRIPTOR.message_types_by_name['SILIAO'] = _SILIAO
DESCRIPTOR.message_types_by_name['SILIAO_ARRAY'] = _SILIAO_ARRAY

SILIAO = _reflection.GeneratedProtocolMessageType('SILIAO', (_message.Message,), dict(
  DESCRIPTOR = _SILIAO,
  __module__ = 'proto.siliao_data_pb2'
  # @@protoc_insertion_point(class_scope:com.game.framework.resource.data.SILIAO)
  ))
_sym_db.RegisterMessage(SILIAO)

SILIAO_ARRAY = _reflection.GeneratedProtocolMessageType('SILIAO_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _SILIAO_ARRAY,
  __module__ = 'proto.siliao_data_pb2'
  # @@protoc_insertion_point(class_scope:com.game.framework.resource.data.SILIAO_ARRAY)
  ))
_sym_db.RegisterMessage(SILIAO_ARRAY)


# @@protoc_insertion_point(module_scope)
