// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user_init_item_data.proto

package com.game.server.data;

public final class UserInitItemData {
  private UserInitItemData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface USER_INIT_ITEMOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.server.data.USER_INIT_ITEM)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 物品ID 
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 物品ID 
     * </pre>
     */
    int getId();

    /**
     * <code>optional int32 item_qty = 2 [default = 0];</code>
     *
     * <pre>
     ** 物品数量 
     * </pre>
     */
    boolean hasItemQty();
    /**
     * <code>optional int32 item_qty = 2 [default = 0];</code>
     *
     * <pre>
     ** 物品数量 
     * </pre>
     */
    int getItemQty();
  }
  /**
   * Protobuf type {@code com.game.server.data.USER_INIT_ITEM}
   */
  public static final class USER_INIT_ITEM extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.game.server.data.USER_INIT_ITEM)
      USER_INIT_ITEMOrBuilder {
    // Use USER_INIT_ITEM.newBuilder() to construct.
    private USER_INIT_ITEM(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private USER_INIT_ITEM(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final USER_INIT_ITEM defaultInstance;
    public static USER_INIT_ITEM getDefaultInstance() {
      return defaultInstance;
    }

    public USER_INIT_ITEM getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private USER_INIT_ITEM(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              itemQty_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.server.data.UserInitItemData.USER_INIT_ITEM.class, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder.class);
    }

    public static com.google.protobuf.Parser<USER_INIT_ITEM> PARSER =
        new com.google.protobuf.AbstractParser<USER_INIT_ITEM>() {
      public USER_INIT_ITEM parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new USER_INIT_ITEM(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<USER_INIT_ITEM> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 物品ID 
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 物品ID 
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int ITEM_QTY_FIELD_NUMBER = 2;
    private int itemQty_;
    /**
     * <code>optional int32 item_qty = 2 [default = 0];</code>
     *
     * <pre>
     ** 物品数量 
     * </pre>
     */
    public boolean hasItemQty() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 item_qty = 2 [default = 0];</code>
     *
     * <pre>
     ** 物品数量 
     * </pre>
     */
    public int getItemQty() {
      return itemQty_;
    }

    private void initFields() {
      id_ = 0;
      itemQty_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, itemQty_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemQty_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.server.data.UserInitItemData.USER_INIT_ITEM prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.server.data.USER_INIT_ITEM}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.server.data.USER_INIT_ITEM)
        com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.server.data.UserInitItemData.USER_INIT_ITEM.class, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder.class);
      }

      // Construct using com.game.server.data.UserInitItemData.USER_INIT_ITEM.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        itemQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_descriptor;
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM getDefaultInstanceForType() {
        return com.game.server.data.UserInitItemData.USER_INIT_ITEM.getDefaultInstance();
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM build() {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM buildPartial() {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM result = new com.game.server.data.UserInitItemData.USER_INIT_ITEM(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemQty_ = itemQty_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.server.data.UserInitItemData.USER_INIT_ITEM) {
          return mergeFrom((com.game.server.data.UserInitItemData.USER_INIT_ITEM)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.server.data.UserInitItemData.USER_INIT_ITEM other) {
        if (other == com.game.server.data.UserInitItemData.USER_INIT_ITEM.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasItemQty()) {
          setItemQty(other.getItemQty());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.server.data.UserInitItemData.USER_INIT_ITEM) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 物品ID 
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 物品ID 
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 物品ID 
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 物品ID 
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int itemQty_ ;
      /**
       * <code>optional int32 item_qty = 2 [default = 0];</code>
       *
       * <pre>
       ** 物品数量 
       * </pre>
       */
      public boolean hasItemQty() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 item_qty = 2 [default = 0];</code>
       *
       * <pre>
       ** 物品数量 
       * </pre>
       */
      public int getItemQty() {
        return itemQty_;
      }
      /**
       * <code>optional int32 item_qty = 2 [default = 0];</code>
       *
       * <pre>
       ** 物品数量 
       * </pre>
       */
      public Builder setItemQty(int value) {
        bitField0_ |= 0x00000002;
        itemQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 item_qty = 2 [default = 0];</code>
       *
       * <pre>
       ** 物品数量 
       * </pre>
       */
      public Builder clearItemQty() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemQty_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.server.data.USER_INIT_ITEM)
    }

    static {
      defaultInstance = new USER_INIT_ITEM(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.server.data.USER_INIT_ITEM)
  }

  public interface USER_INIT_ITEM_ARRAYOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.server.data.USER_INIT_ITEM_ARRAY)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM> 
        getItemsList();
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    com.game.server.data.UserInitItemData.USER_INIT_ITEM getItems(int index);
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    java.util.List<? extends com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.game.server.data.USER_INIT_ITEM_ARRAY}
   */
  public static final class USER_INIT_ITEM_ARRAY extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.game.server.data.USER_INIT_ITEM_ARRAY)
      USER_INIT_ITEM_ARRAYOrBuilder {
    // Use USER_INIT_ITEM_ARRAY.newBuilder() to construct.
    private USER_INIT_ITEM_ARRAY(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private USER_INIT_ITEM_ARRAY(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final USER_INIT_ITEM_ARRAY defaultInstance;
    public static USER_INIT_ITEM_ARRAY getDefaultInstance() {
      return defaultInstance;
    }

    public USER_INIT_ITEM_ARRAY getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private USER_INIT_ITEM_ARRAY(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.game.server.data.UserInitItemData.USER_INIT_ITEM>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(com.game.server.data.UserInitItemData.USER_INIT_ITEM.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.class, com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.Builder.class);
    }

    public static com.google.protobuf.Parser<USER_INIT_ITEM_ARRAY> PARSER =
        new com.google.protobuf.AbstractParser<USER_INIT_ITEM_ARRAY>() {
      public USER_INIT_ITEM_ARRAY parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new USER_INIT_ITEM_ARRAY(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<USER_INIT_ITEM_ARRAY> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM> items_;
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    public java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    public java.util.List<? extends com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    public com.game.server.data.UserInitItemData.USER_INIT_ITEM getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
     */
    public com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.server.data.USER_INIT_ITEM_ARRAY}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.server.data.USER_INIT_ITEM_ARRAY)
        com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAYOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.class, com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.Builder.class);
      }

      // Construct using com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.server.data.UserInitItemData.internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor;
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY getDefaultInstanceForType() {
        return com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.getDefaultInstance();
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY build() {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY buildPartial() {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY result = new com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY) {
          return mergeFrom((com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY other) {
        if (other == com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.server.data.UserInitItemData.USER_INIT_ITEM_ARRAY) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.game.server.data.UserInitItemData.USER_INIT_ITEM>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.server.data.UserInitItemData.USER_INIT_ITEM, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder, com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public com.game.server.data.UserInitItemData.USER_INIT_ITEM getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder setItems(
          int index, com.game.server.data.UserInitItemData.USER_INIT_ITEM value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder setItems(
          int index, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder addItems(com.game.server.data.UserInitItemData.USER_INIT_ITEM value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder addItems(
          int index, com.game.server.data.UserInitItemData.USER_INIT_ITEM value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder addItems(
          com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder addItems(
          int index, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.game.server.data.UserInitItemData.USER_INIT_ITEM> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public java.util.List<? extends com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.game.server.data.UserInitItemData.USER_INIT_ITEM.getDefaultInstance());
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.game.server.data.UserInitItemData.USER_INIT_ITEM.getDefaultInstance());
      }
      /**
       * <code>repeated .com.game.server.data.USER_INIT_ITEM items = 1;</code>
       */
      public java.util.List<com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.server.data.UserInitItemData.USER_INIT_ITEM, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder, com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.server.data.UserInitItemData.USER_INIT_ITEM, com.game.server.data.UserInitItemData.USER_INIT_ITEM.Builder, com.game.server.data.UserInitItemData.USER_INIT_ITEMOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.game.server.data.USER_INIT_ITEM_ARRAY)
    }

    static {
      defaultInstance = new USER_INIT_ITEM_ARRAY(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.server.data.USER_INIT_ITEM_ARRAY)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_server_data_USER_INIT_ITEM_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_server_data_USER_INIT_ITEM_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037proto/user_init_item_data.proto\022\024com.g" +
      "ame.server.data\"4\n\016USER_INIT_ITEM\022\r\n\002id\030" +
      "\001 \002(\005:\0010\022\023\n\010item_qty\030\002 \001(\005:\0010\"K\n\024USER_IN" +
      "IT_ITEM_ARRAY\0223\n\005items\030\001 \003(\0132$.com.game." +
      "server.data.USER_INIT_ITEM"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_server_data_USER_INIT_ITEM_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_server_data_USER_INIT_ITEM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_game_server_data_USER_INIT_ITEM_descriptor,
        new java.lang.String[] { "Id", "ItemQty", });
    internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_game_server_data_USER_INIT_ITEM_ARRAY_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
