// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/dami_bytes.proto

package com.game.framework.resource.data;

public final class DamiBytes {
  private DamiBytes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DAMIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.framework.resource.data.DAMI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 索引 
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 索引 
     * </pre>
     */
    int getId();

    /**
     * <code>optional int32 dami_spd = 2 [default = 0];</code>
     *
     * <pre>
     ** 生长速度 
     * </pre>
     */
    boolean hasDamiSpd();
    /**
     * <code>optional int32 dami_spd = 2 [default = 0];</code>
     *
     * <pre>
     ** 生长速度 
     * </pre>
     */
    int getDamiSpd();

    /**
     * <code>optional int32 dami_cap = 3 [default = 0];</code>
     *
     * <pre>
     ** 单次最高产量 
     * </pre>
     */
    boolean hasDamiCap();
    /**
     * <code>optional int32 dami_cap = 3 [default = 0];</code>
     *
     * <pre>
     ** 单次最高产量 
     * </pre>
     */
    int getDamiCap();
  }
  /**
   * Protobuf type {@code com.game.framework.resource.data.DAMI}
   */
  public static final class DAMI extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.game.framework.resource.data.DAMI)
      DAMIOrBuilder {
    // Use DAMI.newBuilder() to construct.
    private DAMI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DAMI(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DAMI defaultInstance;
    public static DAMI getDefaultInstance() {
      return defaultInstance;
    }

    public DAMI getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DAMI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              damiSpd_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              damiCap_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.resource.data.DamiBytes.DAMI.class, com.game.framework.resource.data.DamiBytes.DAMI.Builder.class);
    }

    public static com.google.protobuf.Parser<DAMI> PARSER =
        new com.google.protobuf.AbstractParser<DAMI>() {
      public DAMI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DAMI(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DAMI> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 索引 
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1 [default = 0];</code>
     *
     * <pre>
     ** 索引 
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int DAMI_SPD_FIELD_NUMBER = 2;
    private int damiSpd_;
    /**
     * <code>optional int32 dami_spd = 2 [default = 0];</code>
     *
     * <pre>
     ** 生长速度 
     * </pre>
     */
    public boolean hasDamiSpd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 dami_spd = 2 [default = 0];</code>
     *
     * <pre>
     ** 生长速度 
     * </pre>
     */
    public int getDamiSpd() {
      return damiSpd_;
    }

    public static final int DAMI_CAP_FIELD_NUMBER = 3;
    private int damiCap_;
    /**
     * <code>optional int32 dami_cap = 3 [default = 0];</code>
     *
     * <pre>
     ** 单次最高产量 
     * </pre>
     */
    public boolean hasDamiCap() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 dami_cap = 3 [default = 0];</code>
     *
     * <pre>
     ** 单次最高产量 
     * </pre>
     */
    public int getDamiCap() {
      return damiCap_;
    }

    private void initFields() {
      id_ = 0;
      damiSpd_ = 0;
      damiCap_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, damiSpd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, damiCap_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, damiSpd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, damiCap_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.resource.data.DamiBytes.DAMI prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.resource.data.DAMI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.framework.resource.data.DAMI)
        com.game.framework.resource.data.DamiBytes.DAMIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.resource.data.DamiBytes.DAMI.class, com.game.framework.resource.data.DamiBytes.DAMI.Builder.class);
      }

      // Construct using com.game.framework.resource.data.DamiBytes.DAMI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        damiSpd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        damiCap_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_descriptor;
      }

      public com.game.framework.resource.data.DamiBytes.DAMI getDefaultInstanceForType() {
        return com.game.framework.resource.data.DamiBytes.DAMI.getDefaultInstance();
      }

      public com.game.framework.resource.data.DamiBytes.DAMI build() {
        com.game.framework.resource.data.DamiBytes.DAMI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.resource.data.DamiBytes.DAMI buildPartial() {
        com.game.framework.resource.data.DamiBytes.DAMI result = new com.game.framework.resource.data.DamiBytes.DAMI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.damiSpd_ = damiSpd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.damiCap_ = damiCap_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.resource.data.DamiBytes.DAMI) {
          return mergeFrom((com.game.framework.resource.data.DamiBytes.DAMI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.resource.data.DamiBytes.DAMI other) {
        if (other == com.game.framework.resource.data.DamiBytes.DAMI.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDamiSpd()) {
          setDamiSpd(other.getDamiSpd());
        }
        if (other.hasDamiCap()) {
          setDamiCap(other.getDamiCap());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.resource.data.DamiBytes.DAMI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.resource.data.DamiBytes.DAMI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 索引 
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 索引 
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 索引 
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1 [default = 0];</code>
       *
       * <pre>
       ** 索引 
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int damiSpd_ ;
      /**
       * <code>optional int32 dami_spd = 2 [default = 0];</code>
       *
       * <pre>
       ** 生长速度 
       * </pre>
       */
      public boolean hasDamiSpd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 dami_spd = 2 [default = 0];</code>
       *
       * <pre>
       ** 生长速度 
       * </pre>
       */
      public int getDamiSpd() {
        return damiSpd_;
      }
      /**
       * <code>optional int32 dami_spd = 2 [default = 0];</code>
       *
       * <pre>
       ** 生长速度 
       * </pre>
       */
      public Builder setDamiSpd(int value) {
        bitField0_ |= 0x00000002;
        damiSpd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dami_spd = 2 [default = 0];</code>
       *
       * <pre>
       ** 生长速度 
       * </pre>
       */
      public Builder clearDamiSpd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        damiSpd_ = 0;
        onChanged();
        return this;
      }

      private int damiCap_ ;
      /**
       * <code>optional int32 dami_cap = 3 [default = 0];</code>
       *
       * <pre>
       ** 单次最高产量 
       * </pre>
       */
      public boolean hasDamiCap() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 dami_cap = 3 [default = 0];</code>
       *
       * <pre>
       ** 单次最高产量 
       * </pre>
       */
      public int getDamiCap() {
        return damiCap_;
      }
      /**
       * <code>optional int32 dami_cap = 3 [default = 0];</code>
       *
       * <pre>
       ** 单次最高产量 
       * </pre>
       */
      public Builder setDamiCap(int value) {
        bitField0_ |= 0x00000004;
        damiCap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dami_cap = 3 [default = 0];</code>
       *
       * <pre>
       ** 单次最高产量 
       * </pre>
       */
      public Builder clearDamiCap() {
        bitField0_ = (bitField0_ & ~0x00000004);
        damiCap_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.resource.data.DAMI)
    }

    static {
      defaultInstance = new DAMI(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.resource.data.DAMI)
  }

  public interface DAMI_ARRAYOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.framework.resource.data.DAMI_ARRAY)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    java.util.List<com.game.framework.resource.data.DamiBytes.DAMI> 
        getItemsList();
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    com.game.framework.resource.data.DamiBytes.DAMI getItems(int index);
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    java.util.List<? extends com.game.framework.resource.data.DamiBytes.DAMIOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    com.game.framework.resource.data.DamiBytes.DAMIOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.game.framework.resource.data.DAMI_ARRAY}
   */
  public static final class DAMI_ARRAY extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.game.framework.resource.data.DAMI_ARRAY)
      DAMI_ARRAYOrBuilder {
    // Use DAMI_ARRAY.newBuilder() to construct.
    private DAMI_ARRAY(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DAMI_ARRAY(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DAMI_ARRAY defaultInstance;
    public static DAMI_ARRAY getDefaultInstance() {
      return defaultInstance;
    }

    public DAMI_ARRAY getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DAMI_ARRAY(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.game.framework.resource.data.DamiBytes.DAMI>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(com.game.framework.resource.data.DamiBytes.DAMI.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_ARRAY_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.class, com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.Builder.class);
    }

    public static com.google.protobuf.Parser<DAMI_ARRAY> PARSER =
        new com.google.protobuf.AbstractParser<DAMI_ARRAY>() {
      public DAMI_ARRAY parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DAMI_ARRAY(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DAMI_ARRAY> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.game.framework.resource.data.DamiBytes.DAMI> items_;
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    public java.util.List<com.game.framework.resource.data.DamiBytes.DAMI> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    public java.util.List<? extends com.game.framework.resource.data.DamiBytes.DAMIOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    public com.game.framework.resource.data.DamiBytes.DAMI getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
     */
    public com.game.framework.resource.data.DamiBytes.DAMIOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.resource.data.DamiBytes.DAMI_ARRAY prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.resource.data.DAMI_ARRAY}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.framework.resource.data.DAMI_ARRAY)
        com.game.framework.resource.data.DamiBytes.DAMI_ARRAYOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_ARRAY_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.class, com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.Builder.class);
      }

      // Construct using com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.resource.data.DamiBytes.internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor;
      }

      public com.game.framework.resource.data.DamiBytes.DAMI_ARRAY getDefaultInstanceForType() {
        return com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.getDefaultInstance();
      }

      public com.game.framework.resource.data.DamiBytes.DAMI_ARRAY build() {
        com.game.framework.resource.data.DamiBytes.DAMI_ARRAY result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.resource.data.DamiBytes.DAMI_ARRAY buildPartial() {
        com.game.framework.resource.data.DamiBytes.DAMI_ARRAY result = new com.game.framework.resource.data.DamiBytes.DAMI_ARRAY(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.resource.data.DamiBytes.DAMI_ARRAY) {
          return mergeFrom((com.game.framework.resource.data.DamiBytes.DAMI_ARRAY)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.resource.data.DamiBytes.DAMI_ARRAY other) {
        if (other == com.game.framework.resource.data.DamiBytes.DAMI_ARRAY.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.resource.data.DamiBytes.DAMI_ARRAY parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.resource.data.DamiBytes.DAMI_ARRAY) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.framework.resource.data.DamiBytes.DAMI> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.game.framework.resource.data.DamiBytes.DAMI>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.framework.resource.data.DamiBytes.DAMI, com.game.framework.resource.data.DamiBytes.DAMI.Builder, com.game.framework.resource.data.DamiBytes.DAMIOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public java.util.List<com.game.framework.resource.data.DamiBytes.DAMI> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public com.game.framework.resource.data.DamiBytes.DAMI getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder setItems(
          int index, com.game.framework.resource.data.DamiBytes.DAMI value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder setItems(
          int index, com.game.framework.resource.data.DamiBytes.DAMI.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder addItems(com.game.framework.resource.data.DamiBytes.DAMI value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder addItems(
          int index, com.game.framework.resource.data.DamiBytes.DAMI value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder addItems(
          com.game.framework.resource.data.DamiBytes.DAMI.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder addItems(
          int index, com.game.framework.resource.data.DamiBytes.DAMI.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.game.framework.resource.data.DamiBytes.DAMI> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public com.game.framework.resource.data.DamiBytes.DAMI.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public com.game.framework.resource.data.DamiBytes.DAMIOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public java.util.List<? extends com.game.framework.resource.data.DamiBytes.DAMIOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public com.game.framework.resource.data.DamiBytes.DAMI.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.game.framework.resource.data.DamiBytes.DAMI.getDefaultInstance());
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public com.game.framework.resource.data.DamiBytes.DAMI.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.game.framework.resource.data.DamiBytes.DAMI.getDefaultInstance());
      }
      /**
       * <code>repeated .com.game.framework.resource.data.DAMI items = 1;</code>
       */
      public java.util.List<com.game.framework.resource.data.DamiBytes.DAMI.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.framework.resource.data.DamiBytes.DAMI, com.game.framework.resource.data.DamiBytes.DAMI.Builder, com.game.framework.resource.data.DamiBytes.DAMIOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.framework.resource.data.DamiBytes.DAMI, com.game.framework.resource.data.DamiBytes.DAMI.Builder, com.game.framework.resource.data.DamiBytes.DAMIOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.resource.data.DAMI_ARRAY)
    }

    static {
      defaultInstance = new DAMI_ARRAY(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.resource.data.DAMI_ARRAY)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_resource_data_DAMI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_resource_data_DAMI_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_resource_data_DAMI_ARRAY_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/dami_bytes.proto\022 com.game.frame" +
      "work.resource.data\"?\n\004DAMI\022\r\n\002id\030\001 \002(\005:\001" +
      "0\022\023\n\010dami_spd\030\002 \001(\005:\0010\022\023\n\010dami_cap\030\003 \001(\005" +
      ":\0010\"C\n\nDAMI_ARRAY\0225\n\005items\030\001 \003(\0132&.com.g" +
      "ame.framework.resource.data.DAMI"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_framework_resource_data_DAMI_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_framework_resource_data_DAMI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_game_framework_resource_data_DAMI_descriptor,
        new java.lang.String[] { "Id", "DamiSpd", "DamiCap", });
    internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_game_framework_resource_data_DAMI_ARRAY_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_game_framework_resource_data_DAMI_ARRAY_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
