// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.game.framework.protocol;

public final class Room {
  private Room() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TCSCreateGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.game.framework.protocol.TCSCreateGroup}
   */
  public static final class TCSCreateGroup extends
      com.google.protobuf.GeneratedMessage
      implements TCSCreateGroupOrBuilder {
    // Use TCSCreateGroup.newBuilder() to construct.
    private TCSCreateGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TCSCreateGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TCSCreateGroup defaultInstance;
    public static TCSCreateGroup getDefaultInstance() {
      return defaultInstance;
    }

    public TCSCreateGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TCSCreateGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSCreateGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.protocol.Room.TCSCreateGroup.class, com.game.framework.protocol.Room.TCSCreateGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<TCSCreateGroup> PARSER =
        new com.google.protobuf.AbstractParser<TCSCreateGroup>() {
      public TCSCreateGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TCSCreateGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TCSCreateGroup> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSCreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.protocol.Room.TCSCreateGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.protocol.TCSCreateGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.protocol.Room.TCSCreateGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSCreateGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.protocol.Room.TCSCreateGroup.class, com.game.framework.protocol.Room.TCSCreateGroup.Builder.class);
      }

      // Construct using com.game.framework.protocol.Room.TCSCreateGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor;
      }

      public com.game.framework.protocol.Room.TCSCreateGroup getDefaultInstanceForType() {
        return com.game.framework.protocol.Room.TCSCreateGroup.getDefaultInstance();
      }

      public com.game.framework.protocol.Room.TCSCreateGroup build() {
        com.game.framework.protocol.Room.TCSCreateGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.protocol.Room.TCSCreateGroup buildPartial() {
        com.game.framework.protocol.Room.TCSCreateGroup result = new com.game.framework.protocol.Room.TCSCreateGroup(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.protocol.Room.TCSCreateGroup) {
          return mergeFrom((com.game.framework.protocol.Room.TCSCreateGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.protocol.Room.TCSCreateGroup other) {
        if (other == com.game.framework.protocol.Room.TCSCreateGroup.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.protocol.Room.TCSCreateGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.protocol.Room.TCSCreateGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.protocol.TCSCreateGroup)
    }

    static {
      defaultInstance = new TCSCreateGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.protocol.TCSCreateGroup)
  }

  public interface TSCCreateGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 groupId = 1;
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    boolean hasGroupId();
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    long getGroupId();
  }
  /**
   * Protobuf type {@code com.game.framework.protocol.TSCCreateGroup}
   */
  public static final class TSCCreateGroup extends
      com.google.protobuf.GeneratedMessage
      implements TSCCreateGroupOrBuilder {
    // Use TSCCreateGroup.newBuilder() to construct.
    private TSCCreateGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TSCCreateGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TSCCreateGroup defaultInstance;
    public static TSCCreateGroup getDefaultInstance() {
      return defaultInstance;
    }

    public TSCCreateGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TSCCreateGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              groupId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCCreateGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.protocol.Room.TSCCreateGroup.class, com.game.framework.protocol.Room.TSCCreateGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<TSCCreateGroup> PARSER =
        new com.google.protobuf.AbstractParser<TSCCreateGroup>() {
      public TSCCreateGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TSCCreateGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TSCCreateGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 groupId = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private long groupId_;
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    public long getGroupId() {
      return groupId_;
    }

    private void initFields() {
      groupId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, groupId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCCreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.protocol.Room.TSCCreateGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.protocol.TSCCreateGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.protocol.Room.TSCCreateGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCCreateGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.protocol.Room.TSCCreateGroup.class, com.game.framework.protocol.Room.TSCCreateGroup.Builder.class);
      }

      // Construct using com.game.framework.protocol.Room.TSCCreateGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor;
      }

      public com.game.framework.protocol.Room.TSCCreateGroup getDefaultInstanceForType() {
        return com.game.framework.protocol.Room.TSCCreateGroup.getDefaultInstance();
      }

      public com.game.framework.protocol.Room.TSCCreateGroup build() {
        com.game.framework.protocol.Room.TSCCreateGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.protocol.Room.TSCCreateGroup buildPartial() {
        com.game.framework.protocol.Room.TSCCreateGroup result = new com.game.framework.protocol.Room.TSCCreateGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.protocol.Room.TSCCreateGroup) {
          return mergeFrom((com.game.framework.protocol.Room.TSCCreateGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.protocol.Room.TSCCreateGroup other) {
        if (other == com.game.framework.protocol.Room.TSCCreateGroup.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.protocol.Room.TSCCreateGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.protocol.Room.TSCCreateGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 groupId = 1;
      private long groupId_ ;
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public Builder setGroupId(long value) {
        bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.protocol.TSCCreateGroup)
    }

    static {
      defaultInstance = new TSCCreateGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.protocol.TSCCreateGroup)
  }

  public interface TCSApplyGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 groupId = 1;
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    boolean hasGroupId();
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    long getGroupId();
  }
  /**
   * Protobuf type {@code com.game.framework.protocol.TCSApplyGroup}
   */
  public static final class TCSApplyGroup extends
      com.google.protobuf.GeneratedMessage
      implements TCSApplyGroupOrBuilder {
    // Use TCSApplyGroup.newBuilder() to construct.
    private TCSApplyGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TCSApplyGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TCSApplyGroup defaultInstance;
    public static TCSApplyGroup getDefaultInstance() {
      return defaultInstance;
    }

    public TCSApplyGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TCSApplyGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              groupId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSApplyGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.protocol.Room.TCSApplyGroup.class, com.game.framework.protocol.Room.TCSApplyGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<TCSApplyGroup> PARSER =
        new com.google.protobuf.AbstractParser<TCSApplyGroup>() {
      public TCSApplyGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TCSApplyGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TCSApplyGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 groupId = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private long groupId_;
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 groupId = 1;</code>
     *
     * <pre>
     * 房间ID
     * </pre>
     */
    public long getGroupId() {
      return groupId_;
    }

    private void initFields() {
      groupId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, groupId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TCSApplyGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.protocol.Room.TCSApplyGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.protocol.TCSApplyGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.protocol.Room.TCSApplyGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSApplyGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.protocol.Room.TCSApplyGroup.class, com.game.framework.protocol.Room.TCSApplyGroup.Builder.class);
      }

      // Construct using com.game.framework.protocol.Room.TCSApplyGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor;
      }

      public com.game.framework.protocol.Room.TCSApplyGroup getDefaultInstanceForType() {
        return com.game.framework.protocol.Room.TCSApplyGroup.getDefaultInstance();
      }

      public com.game.framework.protocol.Room.TCSApplyGroup build() {
        com.game.framework.protocol.Room.TCSApplyGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.protocol.Room.TCSApplyGroup buildPartial() {
        com.game.framework.protocol.Room.TCSApplyGroup result = new com.game.framework.protocol.Room.TCSApplyGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.protocol.Room.TCSApplyGroup) {
          return mergeFrom((com.game.framework.protocol.Room.TCSApplyGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.protocol.Room.TCSApplyGroup other) {
        if (other == com.game.framework.protocol.Room.TCSApplyGroup.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.protocol.Room.TCSApplyGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.protocol.Room.TCSApplyGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 groupId = 1;
      private long groupId_ ;
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public Builder setGroupId(long value) {
        bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 groupId = 1;</code>
       *
       * <pre>
       * 房间ID
       * </pre>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.protocol.TCSApplyGroup)
    }

    static {
      defaultInstance = new TCSApplyGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.protocol.TCSApplyGroup)
  }

  public interface TSCApplyGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool exist = 1;
    /**
     * <code>optional bool exist = 1;</code>
     *
     * <pre>
     * 房间是否存在
     * </pre>
     */
    boolean hasExist();
    /**
     * <code>optional bool exist = 1;</code>
     *
     * <pre>
     * 房间是否存在
     * </pre>
     */
    boolean getExist();

    // optional bool full = 2;
    /**
     * <code>optional bool full = 2;</code>
     *
     * <pre>
     * 房间是否满
     * </pre>
     */
    boolean hasFull();
    /**
     * <code>optional bool full = 2;</code>
     *
     * <pre>
     * 房间是否满
     * </pre>
     */
    boolean getFull();
  }
  /**
   * Protobuf type {@code com.game.framework.protocol.TSCApplyGroup}
   */
  public static final class TSCApplyGroup extends
      com.google.protobuf.GeneratedMessage
      implements TSCApplyGroupOrBuilder {
    // Use TSCApplyGroup.newBuilder() to construct.
    private TSCApplyGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TSCApplyGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TSCApplyGroup defaultInstance;
    public static TSCApplyGroup getDefaultInstance() {
      return defaultInstance;
    }

    public TSCApplyGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TSCApplyGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exist_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              full_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCApplyGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.framework.protocol.Room.TSCApplyGroup.class, com.game.framework.protocol.Room.TSCApplyGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<TSCApplyGroup> PARSER =
        new com.google.protobuf.AbstractParser<TSCApplyGroup>() {
      public TSCApplyGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TSCApplyGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TSCApplyGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool exist = 1;
    public static final int EXIST_FIELD_NUMBER = 1;
    private boolean exist_;
    /**
     * <code>optional bool exist = 1;</code>
     *
     * <pre>
     * 房间是否存在
     * </pre>
     */
    public boolean hasExist() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool exist = 1;</code>
     *
     * <pre>
     * 房间是否存在
     * </pre>
     */
    public boolean getExist() {
      return exist_;
    }

    // optional bool full = 2;
    public static final int FULL_FIELD_NUMBER = 2;
    private boolean full_;
    /**
     * <code>optional bool full = 2;</code>
     *
     * <pre>
     * 房间是否满
     * </pre>
     */
    public boolean hasFull() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool full = 2;</code>
     *
     * <pre>
     * 房间是否满
     * </pre>
     */
    public boolean getFull() {
      return full_;
    }

    private void initFields() {
      exist_ = false;
      full_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, exist_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, full_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, exist_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, full_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.framework.protocol.Room.TSCApplyGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.framework.protocol.Room.TSCApplyGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.framework.protocol.TSCApplyGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.framework.protocol.Room.TSCApplyGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCApplyGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.framework.protocol.Room.TSCApplyGroup.class, com.game.framework.protocol.Room.TSCApplyGroup.Builder.class);
      }

      // Construct using com.game.framework.protocol.Room.TSCApplyGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exist_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        full_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.framework.protocol.Room.internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor;
      }

      public com.game.framework.protocol.Room.TSCApplyGroup getDefaultInstanceForType() {
        return com.game.framework.protocol.Room.TSCApplyGroup.getDefaultInstance();
      }

      public com.game.framework.protocol.Room.TSCApplyGroup build() {
        com.game.framework.protocol.Room.TSCApplyGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.framework.protocol.Room.TSCApplyGroup buildPartial() {
        com.game.framework.protocol.Room.TSCApplyGroup result = new com.game.framework.protocol.Room.TSCApplyGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exist_ = exist_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.full_ = full_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.framework.protocol.Room.TSCApplyGroup) {
          return mergeFrom((com.game.framework.protocol.Room.TSCApplyGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.framework.protocol.Room.TSCApplyGroup other) {
        if (other == com.game.framework.protocol.Room.TSCApplyGroup.getDefaultInstance()) return this;
        if (other.hasExist()) {
          setExist(other.getExist());
        }
        if (other.hasFull()) {
          setFull(other.getFull());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.framework.protocol.Room.TSCApplyGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.framework.protocol.Room.TSCApplyGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool exist = 1;
      private boolean exist_ ;
      /**
       * <code>optional bool exist = 1;</code>
       *
       * <pre>
       * 房间是否存在
       * </pre>
       */
      public boolean hasExist() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool exist = 1;</code>
       *
       * <pre>
       * 房间是否存在
       * </pre>
       */
      public boolean getExist() {
        return exist_;
      }
      /**
       * <code>optional bool exist = 1;</code>
       *
       * <pre>
       * 房间是否存在
       * </pre>
       */
      public Builder setExist(boolean value) {
        bitField0_ |= 0x00000001;
        exist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool exist = 1;</code>
       *
       * <pre>
       * 房间是否存在
       * </pre>
       */
      public Builder clearExist() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exist_ = false;
        onChanged();
        return this;
      }

      // optional bool full = 2;
      private boolean full_ ;
      /**
       * <code>optional bool full = 2;</code>
       *
       * <pre>
       * 房间是否满
       * </pre>
       */
      public boolean hasFull() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool full = 2;</code>
       *
       * <pre>
       * 房间是否满
       * </pre>
       */
      public boolean getFull() {
        return full_;
      }
      /**
       * <code>optional bool full = 2;</code>
       *
       * <pre>
       * 房间是否满
       * </pre>
       */
      public Builder setFull(boolean value) {
        bitField0_ |= 0x00000002;
        full_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool full = 2;</code>
       *
       * <pre>
       * 房间是否满
       * </pre>
       */
      public Builder clearFull() {
        bitField0_ = (bitField0_ & ~0x00000002);
        full_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.framework.protocol.TSCApplyGroup)
    }

    static {
      defaultInstance = new TSCApplyGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.framework.protocol.TSCApplyGroup)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_protocol_TCSCreateGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_protocol_TSCCreateGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_protocol_TCSApplyGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_framework_protocol_TSCApplyGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\022\033com.game.framework.protoco" +
      "l\"\020\n\016TCSCreateGroup\"!\n\016TSCCreateGroup\022\017\n" +
      "\007groupId\030\001 \001(\003\" \n\rTCSApplyGroup\022\017\n\007group" +
      "Id\030\001 \001(\003\",\n\rTSCApplyGroup\022\r\n\005exist\030\001 \001(\010" +
      "\022\014\n\004full\030\002 \001(\010B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_framework_protocol_TCSCreateGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_protocol_TCSCreateGroup_descriptor,
              new java.lang.String[] { });
          internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_framework_protocol_TSCCreateGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_protocol_TSCCreateGroup_descriptor,
              new java.lang.String[] { "GroupId", });
          internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_game_framework_protocol_TCSApplyGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_protocol_TCSApplyGroup_descriptor,
              new java.lang.String[] { "GroupId", });
          internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_game_framework_protocol_TSCApplyGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_framework_protocol_TSCApplyGroup_descriptor,
              new java.lang.String[] { "Exist", "Full", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
